swagger: "2.0"
info:
  version: 0.0.2
  title: Buschallange
  description: Buschallange
  contact: 
      email: ventura.leandro@gmail.com
host: localhost:8000
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
    
securityDefinitions:
  BasicAuth:
    type: basic
    
security:
  - BasicAuth: []    
paths:   

  /home/:
    x-swagger-router-controller: apiController
    get:
      tags:
      - "API" 
      description: Verifica Api Ativa
      operationId: processaHome 
      responses:
        200:
          description: Objeto de orçamento
          schema:
            $ref: "#/definitions/inline_response_200"             
#################################################################################
#                       API de BusChallenge  - Usuarios                         #
#################################################################################    
  /users:
    x-swagger-router-controller: passageiroController
    post:
        tags:
          - "Passageiro"
        summary: Cadatro
        description: Grava Passageiro (Usuario)
        operationId: addPassageiro
        parameters:
          - in: body
            name: body
            description: Objeto novo Passageiro
            required: true
            schema:
              $ref: '#/definitions/bodyRequest'    
        responses:
          200:
            description: Sucesso
            schema:
              $ref: '#/definitions/inline_response_200'  
    delete:
        tags:
          - "Passageiro"
        summary: deleta usuario
        description: deleta Passageiro (Usuario)
        operationId: delPassageiro
        parameters:
          - in: body
            name: body
            description: Card do Passageiro
            required: true
            schema:
              $ref: '#/definitions/bodyRequest'    
        responses:
          200:
            description: Sucesso
            schema:
              $ref: '#/definitions/inline_response_200'  

#################################################################################
#                       API de BusChallenge  - Débitos                          #
#################################################################################   

  /debits:
    x-swagger-router-controller: lancamentoController
    post:
        tags:
          - "Passageiro"
        summary: Cadatro
        description: Grava Lancamento de Débito
        operationId: addDebito
        parameters:
          - in: body
            name: body
            description: Objeto novo de Débito
            required: true
            schema:
              $ref: '#/definitions/bodyRequest'    
        responses:
          200:
            description: Sucesso
            schema:
              $ref: '#/definitions/inline_response_200'           
    get:
      tags:
      - "debits" 
      summary: Busca
      description: Retorna array de lançamentos
      operationId: getLancamentosDebitos
      parameters:
        - in: query
          name: initialDate
          type: string
          required: false     
        - in: query
          name: finalDate
          type: string
          required: false             
        - in: query
          name: cardId
          type: string
          required: false     
      responses:
        200:
          description: Sucesso
          schema:
            $ref: "#/definitions/arrayResponseDebitos"   

#################################################################################
#                                   RESPONSE                                    #
#################################################################################
definitions:

  inline_response_200:
    type: object

  bodyRequest:
    type: object      

  arrayResponseDebitos:
    properties:
      id:
        type: string
      debitedAt:
        type: string
      value:
        type: integer